### ISSUE TITLE
sqitch not found

### ISSUE THREAD

**Issue by TheAngryByrd** [docteurklein/docker-sqitch#3]
When I ran the command I end up with sqitch not found: 

```
docker run --rm docteurklein/sqitch:pgsql
/bin/sh: 1: [sqitch]: not found
```

I'm on OSX using docker-machine. 

Am I doing something silly?

**Comment by RobPrecious** [comment]
+1

**Comment by meticulo3366** [comment]
need examples of how this is used correctly, this is still issue..

**Comment by meticulo3366** [comment]
I made a docker image that works out of the box, probably should be merged into this one!

[docker image on dockerhub](https://hub.docker.com/r/meticulo3366/sqitch/)

[github repo feel free to clone](https://github.com/meticulo3366/docker-sqitch)

**Comment by aleksandr-vin** [comment]
Specifying `--entrypoint=sqitch` helps

**Comment by docteurklein** [comment]
related to theory/sqitch#303

**Comment by docteurklein** [comment]
should be fixed now.
